### ISSUE TITLE
--config parameter is not recognized

### ISSUE THREAD

**Issue by seakayone** [nuxeo/FunkLoad#141]
when I start the fl-run-test or fl-run-bench commands with

  fl-run-test -v --config test_Auth.py
or 

I get the output:
  fl-run-test: error: no such option: --config
and 
  fl-run-bench: error: no such option: --config

using 1.16.1 on zsh/OS X

the current 1.6.1 documentation says it is supported though: 
http://funkload.nuxeo.org/usage-fl-run-test.html
http://funkload.nuxeo.org/usage-fl-run-bench.html

**Comment by madarche** [comment]
The `--config` option is only available from the latest source in Git and will be available in the future 1.17.0. It's not available in the 1.16.x release as the doc states it.

To use the future 1.17.0, you can:

    $ git clone https://github.com/nuxeo/FunkLoad.git funkload
    $ cd funkload
    $ virtualenv ~/opt/funkload.virtualenv
    $ . ~/opt/funkload.virtualenv/bin/activate
    $ python setup.py build
    $ python setup.py install
    $ cd path/to/your/tests
    $ fl-run-bench --help
    --config=CONFIG is available
